/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.jnxplus

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'gradle.plugin.greeting' plugin.*/
class GradlePluginTest extends Specification {
  def "plugin registers task"() {
    given:
    def project = ProjectBuilder.builder().build()

    when:
    project.plugins.apply("io.github.jnxplus")

    then:
    project.tasks.findByName("projectDependencyTask") != null
  }
}
