/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package jnxplus.gradle.plugin

import spock.lang.Specification
import spock.lang.TempDir
import org.gradle.testkit.runner.GradleRunner

/**
 * A simple functional test for the 'jnxplus.gradle.plugin.projects' plugin.
 */
class GradlePluginPluginFunctionalTest extends Specification {
    @TempDir
    private File projectDir

    private getBuildFile() {
        new File(projectDir, "build.gradle")
    }

    private getSettingsFile() {
        new File(projectDir, "settings.gradle")
    }

    def "can run task"() {
        given:
        settingsFile << ""
        buildFile << """
plugins {
    id('jnxplus.gradle.plugin')
}
"""

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("projectDependencyReport", "--outputFile", "example.json")
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.contains("Task ran for projectDependencyReport")
    }
}
