/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package jnxplus.gradle.plugin


import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * Deps graph plugin.*/
class GradlePluginPlugin implements Plugin<Project> {

  void apply(Project project) {
    // Register a task
    project.tasks.register("projectDependencyReport", ProjectDependencyTask)
  }

}
